# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('material', models.CharField(max_length=255)),
            ],
        ),
    ]
