# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_item_info', '0003_auto_20170517_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminfo',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='iteminfo',
            name='size',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='iteminfo',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
