# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_item_info', '0004_auto_20170517_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminfo',
            name='weight',
            field=models.DecimalField(decimal_places=10, max_digits=50),
        ),
    ]
