# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_item_info', '0005_auto_20170517_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminfo',
            name='item_img1',
            field=models.FileField(default='default.jpg', upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iteminfo',
            name='item_img2',
            field=models.FileField(default='default.jpg', upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iteminfo',
            name='item_img3',
            field=models.FileField(default='default.jpg', upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iteminfo',
            name='item_img4',
            field=models.FileField(default='default.jpg', upload_to='img/'),
            preserve_default=False,
        ),
    ]
