# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_item_info', '0006_auto_20170528_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminfo',
            name='item_img1',
            field=models.FileField(upload_to='http://127.0.0.1:8000/static/img/'),
        ),
        migrations.AlterField(
            model_name='iteminfo',
            name='item_img2',
            field=models.FileField(upload_to='http://127.0.0.1:8000/static/img/'),
        ),
        migrations.AlterField(
            model_name='iteminfo',
            name='item_img3',
            field=models.FileField(upload_to='http://127.0.0.1:8000/static/img/'),
        ),
        migrations.AlterField(
            model_name='iteminfo',
            name='item_img4',
            field=models.FileField(upload_to='http://127.0.0.1:8000/static/img/'),
        ),
    ]
