# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_item_info', '0010_auto_20170529_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminfo',
            name='img',
            field=models.FileField(default='default.png', upload_to='db_img/'),
            preserve_default=False,
        ),
    ]
