# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_item_info', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='iteminfo',
            name='size',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='iteminfo',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='iteminfo',
            name='material',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='iteminfo',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
