# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_item_info', '0011_iteminfo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminfo',
            name='img',
            field=models.FileField(upload_to=''),
        ),
    ]
