# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_item_info', '0012_auto_20170529_0413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iteminfo',
            old_name='img',
            new_name='img1',
        ),
        migrations.RemoveField(
            model_name='iteminfo',
            name='ext_img1',
        ),
        migrations.RemoveField(
            model_name='iteminfo',
            name='ext_img2',
        ),
        migrations.RemoveField(
            model_name='iteminfo',
            name='ext_img3',
        ),
        migrations.RemoveField(
            model_name='iteminfo',
            name='ext_img4',
        ),
        migrations.AddField(
            model_name='iteminfo',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iteminfo',
            name='img2',
            field=models.FileField(default='default.png', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iteminfo',
            name='img3',
            field=models.FileField(default='default.png', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iteminfo',
            name='img4',
            field=models.FileField(default='default.png', upload_to=''),
            preserve_default=False,
        ),
    ]
